// <auto-generated />
namespace SleepMakeSense.Migrations.SleepbetaDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedPercievedstresstoUserdata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedPercievedstresstoUserdata));
        
        string IMigrationMetadata.Id
        {
            get { return "201712121917322_added Percieved stress to Userdata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
